package com.oefaspace.supervision_linea;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TMapSectorDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TMAPSECTORDO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "TMAPSECTORDO_ID_GENERATOR", sequenceName = "TMAPSECTORDO_ID_SEQ")
	private java.lang.Long nu_Id_Sector;

	private java.lang.String tx_Codsector;

	private java.lang.String tx_Sector;

	public TMapSectorDO() {
	}

	public java.lang.Long getNu_Id_Sector() {
		return this.nu_Id_Sector;
	}

	public void setNu_Id_Sector(java.lang.Long nu_Id_Sector) {
		this.nu_Id_Sector = nu_Id_Sector;
	}

	public java.lang.String getTx_Codsector() {
		return this.tx_Codsector;
	}

	public void setTx_Codsector(java.lang.String tx_Codsector) {
		this.tx_Codsector = tx_Codsector;
	}

	public java.lang.String getTx_Sector() {
		return this.tx_Sector;
	}

	public void setTx_Sector(java.lang.String tx_Sector) {
		this.tx_Sector = tx_Sector;
	}

	public TMapSectorDO(java.lang.Long nu_Id_Sector,
			java.lang.String tx_Codsector, java.lang.String tx_Sector) {
		this.nu_Id_Sector = nu_Id_Sector;
		this.tx_Codsector = tx_Codsector;
		this.tx_Sector = tx_Sector;
	}

}