package com.oefaspace.supervision_linea;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TMvdDocumDer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TMVDDOCUMDER_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "TMVDDOCUMDER_ID_GENERATOR", sequenceName = "TMVDDOCUMDER_ID_SEQ")
	private java.lang.Long nu_Id_Docum_Der;
	private java.lang.String tx_Nomfile;
	private java.lang.String tx_Usuario_Orig;
	private java.lang.String tx_Usuario_Dest;
	private java.util.Date fe_Fecusureg;
	private java.util.Date fe_Fecusuder;
	private java.lang.String cl_Observ;
	private java.lang.String tx_Estadoreg;
	private java.lang.String tx_Estadoder;
	private java.lang.String tx_Codhtregsiged;
	private java.lang.String tx_Expedsiged;
	private java.lang.String tx_Tokensiged;
	private java.lang.String tx_Uuidalfresco;

	public TMvdDocumDer() {
	}

	public java.lang.Long getNu_Id_Docum_Der() {
		return this.nu_Id_Docum_Der;
	}

	public void setNu_Id_Docum_Der(java.lang.Long nu_Id_Docum_Der) {
		this.nu_Id_Docum_Der = nu_Id_Docum_Der;
	}

	public java.lang.String getTx_Nomfile() {
		return this.tx_Nomfile;
	}

	public void setTx_Nomfile(java.lang.String tx_Nomfile) {
		this.tx_Nomfile = tx_Nomfile;
	}

	public java.lang.String getTx_Usuario_Orig() {
		return this.tx_Usuario_Orig;
	}

	public void setTx_Usuario_Orig(java.lang.String tx_Usuario_Orig) {
		this.tx_Usuario_Orig = tx_Usuario_Orig;
	}

	public java.lang.String getTx_Usuario_Dest() {
		return this.tx_Usuario_Dest;
	}

	public void setTx_Usuario_Dest(java.lang.String tx_Usuario_Dest) {
		this.tx_Usuario_Dest = tx_Usuario_Dest;
	}

	public java.util.Date getFe_Fecusureg() {
		return this.fe_Fecusureg;
	}

	public void setFe_Fecusureg(java.util.Date fe_Fecusureg) {
		this.fe_Fecusureg = fe_Fecusureg;
	}

	public java.util.Date getFe_Fecusuder() {
		return this.fe_Fecusuder;
	}

	public void setFe_Fecusuder(java.util.Date fe_Fecusuder) {
		this.fe_Fecusuder = fe_Fecusuder;
	}

	public java.lang.String getCl_Observ() {
		return this.cl_Observ;
	}

	public void setCl_Observ(java.lang.String cl_Observ) {
		this.cl_Observ = cl_Observ;
	}

	public java.lang.String getTx_Estadoreg() {
		return this.tx_Estadoreg;
	}

	public void setTx_Estadoreg(java.lang.String tx_Estadoreg) {
		this.tx_Estadoreg = tx_Estadoreg;
	}

	public java.lang.String getTx_Estadoder() {
		return this.tx_Estadoder;
	}

	public void setTx_Estadoder(java.lang.String tx_Estadoder) {
		this.tx_Estadoder = tx_Estadoder;
	}

	public java.lang.String getTx_Codhtregsiged() {
		return this.tx_Codhtregsiged;
	}

	public void setTx_Codhtregsiged(java.lang.String tx_Codhtregsiged) {
		this.tx_Codhtregsiged = tx_Codhtregsiged;
	}

	public java.lang.String getTx_Expedsiged() {
		return this.tx_Expedsiged;
	}

	public void setTx_Expedsiged(java.lang.String tx_Expedsiged) {
		this.tx_Expedsiged = tx_Expedsiged;
	}

	public java.lang.String getTx_Tokensiged() {
		return this.tx_Tokensiged;
	}

	public void setTx_Tokensiged(java.lang.String tx_Tokensiged) {
		this.tx_Tokensiged = tx_Tokensiged;
	}

	public java.lang.String getTx_Uuidalfresco() {
		return this.tx_Uuidalfresco;
	}

	public void setTx_Uuidalfresco(java.lang.String tx_Uuidalfresco) {
		this.tx_Uuidalfresco = tx_Uuidalfresco;
	}

	public TMvdDocumDer(java.lang.Long nu_Id_Docum_Der,
			java.lang.String tx_Nomfile, java.lang.String tx_Usuario_Orig,
			java.lang.String tx_Usuario_Dest, java.util.Date fe_Fecusureg,
			java.util.Date fe_Fecusuder, java.lang.String cl_Observ,
			java.lang.String tx_Estadoreg, java.lang.String tx_Estadoder,
			java.lang.String tx_Codhtregsiged, java.lang.String tx_Expedsiged,
			java.lang.String tx_Tokensiged, java.lang.String tx_Uuidalfresco) {
		this.nu_Id_Docum_Der = nu_Id_Docum_Der;
		this.tx_Nomfile = tx_Nomfile;
		this.tx_Usuario_Orig = tx_Usuario_Orig;
		this.tx_Usuario_Dest = tx_Usuario_Dest;
		this.fe_Fecusureg = fe_Fecusureg;
		this.fe_Fecusuder = fe_Fecusuder;
		this.cl_Observ = cl_Observ;
		this.tx_Estadoreg = tx_Estadoreg;
		this.tx_Estadoder = tx_Estadoder;
		this.tx_Codhtregsiged = tx_Codhtregsiged;
		this.tx_Expedsiged = tx_Expedsiged;
		this.tx_Tokensiged = tx_Tokensiged;
		this.tx_Uuidalfresco = tx_Uuidalfresco;
	}

}