package com.oefaspace.supervision_linea;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TMvdFof implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TMVDFOF_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "TMVDFOF_ID_GENERATOR", sequenceName = "TMVDFOF_ID_SEQ")
    private java.lang.Long id;

    public TMvdFof() {
    }
    
    public TMvdFof(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}