package com.oefaspace.supervision_linea;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TMvdDocumDer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TMvdDocumDer() {
    }




}